name: GitHub Action test
run-name: ${{ github.actor}} is testing out GitHub Action 🎉
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🍏 This job's status is ${{ job.status }}"
